In [31]:
import pandas as pd
import spacy

In [32]:
df = pd.read_csv("../data/sample_tickets.csv")
df.head()

  ticket_id                                           text   category
0  TKT-1001  The calendar integration isn't showing events  technical
1  TKT-1002            What is your support response time?    general
2  TKT-1003  How do I transfer my account to another user?    account
3  TKT-1004   Do you offer SOC 2 compliance documentation?    general
4  TKT-1005  How do I revoke access for a former employee?    account

In [33]:
df[['text', 'category']] = df[['text', 'category']].apply(lambda col: col.str.lower())

In [34]:
df.head()

  ticket_id                                           text   category
0  TKT-1001  the calendar integration isn't showing events  technical
1  TKT-1002            what is your support response time?    general
2  TKT-1003  how do i transfer my account to another user?    account
3  TKT-1004   do you offer soc 2 compliance documentation?    general
4  TKT-1005  how do i revoke access for a former employee?    account

In [ ]:
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    try:
        spacy.cli.download("en_core_web_sm")
        nlp = spacy.load("en_core_web_sm")
    except Exception:
        # fallback to a blank English pipeline if download fails
        nlp = spacy.blank("en")
df['text'] = df['text'].apply(lambda text:[tokens.lemma_ for tokens in nlp(text) if not tokens.is_stop and not tokens.is_punct and not tokens.is_alpha])
df['text'].head()

0             [calendar, integration, show, event]
1                     [support, response, time, ?]
2                     [transfer, account, user, ?]
3    [offer, soc, 2, compliance, documentation, ?]
4                    [revoke, access, employee, ?]
Name: text, dtype: object